// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VilaBooking.Infrastructure.Data;

#nullable disable

namespace VilaBooking.Infrastructure.Migrations
{
    [DbContext(typeof(VilaBookingContext))]
    [Migration("20260225141340_AddAmenity")]
    partial class AddAmenity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VilaBooking.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VilaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VilaId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Private Pool",
                            VilaId = 45
                        },
                        new
                        {
                            Id = 2,
                            Name = "Microwave",
                            VilaId = 45
                        },
                        new
                        {
                            Id = 3,
                            Name = "Private Balcony",
                            VilaId = 45
                        },
                        new
                        {
                            Id = 4,
                            Name = "1 king bed and 1 sofa bed",
                            VilaId = 45
                        },
                        new
                        {
                            Id = 5,
                            Name = "Private Plunge Pool",
                            VilaId = 46
                        },
                        new
                        {
                            Id = 6,
                            Name = "Microwave and Mini Refrigerator",
                            VilaId = 46
                        },
                        new
                        {
                            Id = 7,
                            Name = "Private Balcony",
                            VilaId = 46
                        },
                        new
                        {
                            Id = 8,
                            Name = "king bed or 2 double beds",
                            VilaId = 46
                        },
                        new
                        {
                            Id = 9,
                            Name = "Private Pool",
                            VilaId = 47
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jacuzzi",
                            VilaId = 47
                        },
                        new
                        {
                            Id = 11,
                            Name = "Private Balcony",
                            VilaId = 47
                        });
                });

            modelBuilder.Entity("VilaBooking.Domain.Entities.Vila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vilas");
                });

            modelBuilder.Entity("VilaBooking.Domain.Entities.VilaNumber", b =>
                {
                    b.Property<int>("Vila_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VilaId")
                        .HasColumnType("int");

                    b.HasKey("Vila_Number");

                    b.HasIndex("VilaId");

                    b.ToTable("VilaNumbers");
                });

            modelBuilder.Entity("VilaBooking.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("VilaBooking.Domain.Entities.Vila", "Vila")
                        .WithMany()
                        .HasForeignKey("VilaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vila");
                });

            modelBuilder.Entity("VilaBooking.Domain.Entities.VilaNumber", b =>
                {
                    b.HasOne("VilaBooking.Domain.Entities.Vila", "Vila")
                        .WithMany("VilaNumbers")
                        .HasForeignKey("VilaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vila");
                });

            modelBuilder.Entity("VilaBooking.Domain.Entities.Vila", b =>
                {
                    b.Navigation("VilaNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
