// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VilaBookingService.Infrastructure.Data;

#nullable disable

namespace VilaBookingService.Infrastructure.Migrations
{
    [DbContext(typeof(VilaBookingContext))]
    [Migration("20260222104106_ModifyVilaNumber")]
    partial class ModifyVilaNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VilaBookingService.Domain.Entities.Vila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vilas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200m,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300m,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400m,
                            Sqft = 750
                        });
                });

            modelBuilder.Entity("VilaBookingService.Domain.Entities.VilaNumber", b =>
                {
                    b.Property<int>("Vila_Number")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VilaID")
                        .HasColumnType("int");

                    b.HasKey("Vila_Number");

                    b.HasIndex("VilaID");

                    b.ToTable("VilaNumbers");

                    b.HasData(
                        new
                        {
                            Vila_Number = 101,
                            VilaID = 1
                        },
                        new
                        {
                            Vila_Number = 102,
                            VilaID = 1
                        },
                        new
                        {
                            Vila_Number = 103,
                            VilaID = 1
                        },
                        new
                        {
                            Vila_Number = 104,
                            VilaID = 1
                        },
                        new
                        {
                            Vila_Number = 201,
                            VilaID = 2
                        },
                        new
                        {
                            Vila_Number = 202,
                            VilaID = 2
                        },
                        new
                        {
                            Vila_Number = 203,
                            VilaID = 2
                        },
                        new
                        {
                            Vila_Number = 204,
                            VilaID = 2
                        },
                        new
                        {
                            Vila_Number = 302,
                            VilaID = 3
                        },
                        new
                        {
                            Vila_Number = 303,
                            VilaID = 3
                        });
                });

            modelBuilder.Entity("VilaBookingService.Domain.Entities.VilaNumber", b =>
                {
                    b.HasOne("VilaBookingService.Domain.Entities.Vila", "Vila")
                        .WithMany()
                        .HasForeignKey("VilaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vila");
                });
#pragma warning restore 612, 618
        }
    }
}
